### ISSUE TITLE
Add aesthetics

### ISSUE THREAD

**Issue by henriiquecampos** [GDquest/Your-First-Game-Godot-2d-Platformer#16]
- [ ] Coin sprite
- [ ] Portal sprite
- [ ] Enemy sprite
- [ ] Player sprite

Try to maintain a nice flat look as we use in the https://github.com/GDquest/make-pro-2d-games-with-godot

Will the project have support for sfx and music @NathanLovato ? We can use mine to avoid spending time producing them and just focus on their implementation in this project we can use the ones from https://pigdev.itch.io/juans-saga 3rd place in music criterea in the JimJam btw :sunglasses:

**Comment by NathanLovato** [comment]
Please keep the visuals to a minimum. Every feature that you add, like parallax scrolling background, is extra work for the tutorial.

I want minimal UI and no theme. Flat text is enough for the title screen and game over.

> we can use the ones from https://pigdev.itch.io/juans-saga 3rd place in music criterea in the JimJam btw sunglasses

You want the soundtrack to work with the visuals, not pick any and stitch it on the game. You also don't have enough experience with music - the melody and harmony are really off in the video. Let's leave sound out for now. We can always grab a nice CC-licensed loop later.
