### ISSUE TITLE
Consider how coin scoring is done

### ISSUE THREAD

**Issue by razcore-rad** [GDquest/Your-First-Game-Godot-2d-Platformer#18]
At the moment the coins have a set score value and enemies also have a score on kill.

My proposal would be to make it more Mario-like where the enemies drop coins and instead of a general score board we could use the number of coins collected.

What do you think?

**Comment by henriiquecampos** [comment]
Sounds cool to me, especially to introduce instancing, randomization and even some game design concepts, like feedback loops and resource management.

**Comment by NathanLovato** [comment]
Please don't expand the game's scope, this is supposed to be a short series.

**Comment by razcore-rad** [comment]
Alright then
