### ISSUE TITLE
SceneTree.*_scene functions leave the game stuck After pressing the RetryButton, going back to the main menu, or reloading a scene in general, in Godot 3.1, the game gets stuck

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/Your-First-Game-Godot-2d-Platformer#25]

**Comment by henriiquecampos** [comment]
Let me see that, I think that we aren't unpausing the SceneTree properly.

**Comment by NathanLovato** [comment]
I just pushed a small fix, some nodes I had renamed, forgot to update the associated script

**Comment by henriiquecampos** [comment]
I added a fix to that in aad411734b2b8d52083f5d610dc2434ea57f81c3 can you confirm it fixes the bug @NathanLovato ?

**Comment by NathanLovato** [comment]
Yes. Please always use `git pull --rebase` when working on master before you push anything, it ensures that your new commits end up at the end of the history and prevents it from getting messy.
