### ISSUE TITLE
Back to the menu does not work

### ISSUE THREAD

**Issue by Skybic** [GDquest/Your-First-Game-Godot-2d-Platformer#28]
When I playing the game and then pause the game - button "Back to main screen" didn't working.

And thanks for awesome tutorial - it helped me a lot! :)

**Comment by rKinson** [comment]
@Skybic @NathanLovato 

The MainScreenButton doesn't have the Next Scene Path property set.

I set it to "res://src/Screens/MainScreen.tscn" and that fixed it. However it will lead you into another problem which you can follow in #29
