### ISSUE TITLE
Portal Interrupted by Enemy Collision

### ISSUE THREAD

**Issue by werefrog114** [GDquest/Your-First-Game-Godot-2d-Platformer#35]
## Bug report ##

**What is the current behavior?**
The Player enters the Portal and the scene begins to fade out / change to the next scene. This process is interrupted, however, if an Enemy collides with the Player during the fade out, resulting in the Player's death. Since the Portal scene transition is relatively slow, there is a decent window of time in which the Enemy can collide with you. 

You can (barely) see the Pause/Player Died menu overlay through the mostly-opaque ColorRect that was fading in-- screenshot attached.

**What is the expected behavior?**
Ideally, entering the Portal should pause any enemies on the current level.

**Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.** 
1. Position your Player near the level's Portal.
2. Wait for an Enemy to approach, and enter the Portal shortly before collision with the Enemy
3. Watch as chaos ensues ;)

I coded along step-by-step with the Youtube series, just FYI

<img width="1274" alt="Screen Shot 2020-01-19 at 10 49 13 AM" src="https://user-images.githubusercontent.com/60073569/72686417-6107b300-3aa9-11ea-8001-b0591a388bfb.png">

**Comment by NathanLovato** [comment]
Thanks for the report, it's fixed now
