### ISSUE TITLE
MainScreen paused and Score persists on Play Again

### ISSUE THREAD

**Issue by brunosiffredi** [GDquest/Your-First-Game-Godot-2d-Platformer#36]
When entering the MainScreen from the Pause Menu Main Screen Button, the MainScreen is paused. I fixed this by adding the same script present in the Retry Button (get_tree().paused = false)

When you click Play Again on the EndScreen, the Score of the ended game persists on the new game. I fixed this by adding the script "PlayerData.score = 0"

**Comment by NathanLovato** [comment]
Is this an error you had following the tutorial? I just tested both points and:

1. The game isn't paused when going back to the main menu from the pause screen.
2. The score is correctly reset to 0 when pressing play again on the end screen.

Closing this issue for now. If you have other steps I can take to reproduce the issue, please leave a comment and I'll reopen it. The bugs you report should be on the game from this repository, and based on testing the master branch.
