### ISSUE TITLE
MainScreen Menu Not Working

### ISSUE THREAD

**Issue by coBearCoding** [GDquest/Your-First-Game-Godot-2d-Platformer#37]
**I'm submitting a...**

- [x] Bug report.
- [ ] Feature request.

## Bug report ##

**What is the current behavior?**
MainScreen menu not working when the player pauses de game clicks MainScreen then the buttons on that screen don't work.

**What is the expected behavior?**
To be able to play the game or quit

**Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.** 

1. Start the game 
 2. Click play. 
 3. Pause the game
4. Click MainScreen
5. Click play or quit

**Comment by NathanLovato** [comment]
Did you use the version of the game from an older release? The bug is already fixed in the latest version (downloading or cloning from GitHub). That's the one to test before reporting bugs.

Thanks for taking the time to write a report! But as it's already fixed, I'll close this issue now.
