### ISSUE TITLE
Godot 4

### ISSUE THREAD

**Issue by brno32** [GDquest/Your-First-Game-Godot-2d-Platformer#44]
Would you accept a PR that updates this project for Godot 4?

**Comment by NathanLovato** [comment]
While we always appreciate contributions, I think we won't update the main branch of the repository to Godot 4 because it's linked to this old youtube video. So if you contributed a Godot 4 port, we would save it in a secondary branch.

**Comment by brno32** [comment]
Since the C# version is in the `main` branch as a neighbor to the gdscript version, would it make sense to have a godot 4 version in just another folder?

e.g., we'd have `game`, `mono-game`, and maybe `godot4-game`?

**Comment by NathanLovato** [comment]
Sure! That would work. Such a contribution would be welcome.

**Comment by brno32** [comment]
> Sure! That would work. Such a contribution would be welcome.

I've opened a draft PR to welcome your feedback. Porting was harder than I thought it'd be 🤣

**Comment by brno32** [comment]
done in https://github.com/GDQuest/godot-beginner-2d-platformer/pull/45
