### ISSUE TITLE
Add Coins

### ISSUE THREAD

**Issue by henriiquecampos** [GDquest/Your-First-Game-Godot-2d-Platformer#6]
`Coins` are `Area2D` and serve as a reward for the player.  When the player collides with them they will be freed and the player will score.

- [x] Add Coins `Area2D`
- [x] Add support for scoring
- [x] Add Player's `CoinPickupArea2d`, an `Area2D` dedicated to detect collisions with `Coins`

@NathanLovato can we add a `PopLabel` to them, so that when the player picks one, they pop a label on the screen with how much the player scored?

**Comment by razcore-rad** [comment]
I personally thing adding a `PopLabel` is a nice touch, something like they have in Darkest Dungeon. I'm in favor of it :)

**Comment by NathanLovato** [comment]
Go ahead, do this however you'd like, as long as the code stays short and simple

**Comment by NathanLovato** [comment]
The two of you are in charge on this project
